version: "3.6"

services:
  elasticsearch:
    container_name: elasticsearch
    restart: always
    image: elasticsearch:8.6.1
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      test:
        ipv4_address: 172.30.1.3

  app:
    container_name: app
    restart: always
    build:
      context: ../dev
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    volumes:
      - "./:/app"
    ports:
      - 8080:8080
    user: "1000:1000"
    networks:
      test:
        ipv4_address: 172.30.1.2

networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24
